# Generated by Django 4.2.1 on 2023-09-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_number',
            field=models.CharField(default=5, max_length=15),
            preserve_default=False,
        ),
    ]
