# Generated by Django 4.2.1 on 2023-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_customuser_national_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_books',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
